Added second map (map 0 = warehouse)
Does not run - error that disk objects cannot be placed because tries to interpret as boxes - box vertices:
/Users/timothydemaro/Documents/GitHub/RBE550JaneLeeProject
Version:  0.0.49
Traceback (most recent call last):
  File "/Users/timothydemaro/Documents/GitHub/RBE550JaneLeeProject/Examples/example.py", line 460, in <module>
    sim = Simulator(env, rand_obstacles=20, map_selector=0, wrld_size=wrld_size, num_humans=num_humans, global_map_init=True, use_global_knowledge=False)
  File "/Users/timothydemaro/Documents/GitHub/RBE550JaneLeeProject/Examples/example.py", line 362, in __init__
    self.map = Map(env, self.robots, boxes=self.obstacles, definition=definition, lidar_range=lidar_range,
  File "/Users/timothydemaro/Documents/GitHub/RBE550JaneLeeProject/Examples/example.py", line 55, in __init__
    self.box_vertices[box] = np.asarray(self.boxes[box].fixtures[0].shape.vertices)
AttributeError: 'b2CircleShape' object has no attribute 'vertices'